package seers.irda.entity;
// Generated Dec 9, 2015 11:27:45 AM by Hibernate Tools 4.3.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChangeSet generated by hbm2java
 */
@Entity
@Table(name="change_set"
    ,catalog="ir_issues"
)
public class ChangeSet  implements java.io.Serializable {


     private ChangeSetId id;
     private CodeFile codeFile;
     private Revision revision;

    public ChangeSet() {
    }

    public ChangeSet(ChangeSetId id, CodeFile codeFile, Revision revision) {
       this.id = id;
       this.codeFile = codeFile;
       this.revision = revision;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fileId", column=@Column(name="file_id", nullable=false) ), 
        @AttributeOverride(name="revisionId", column=@Column(name="revision_id", nullable=false) ), 
        @AttributeOverride(name="changeType", column=@Column(name="change_type", nullable=false, length=200) ) } )
    public ChangeSetId getId() {
        return this.id;
    }
    
    public void setId(ChangeSetId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="file_id", nullable=false, insertable=false, updatable=false)
    public CodeFile getCodeFile() {
        return this.codeFile;
    }
    
    public void setCodeFile(CodeFile codeFile) {
        this.codeFile = codeFile;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="revision_id", nullable=false, insertable=false, updatable=false)
    public Revision getRevision() {
        return this.revision;
    }
    
    public void setRevision(Revision revision) {
        this.revision = revision;
    }




}


