package seers.irda.entity;
// Generated Dec 9, 2015 11:27:45 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CodeFile generated by hbm2java
 */
@Entity
@Table(name="code_file"
    ,catalog="ir_issues"
    , uniqueConstraints = @UniqueConstraint(columnNames={"file_path", "system_id"}) 
)
public class CodeFile  implements java.io.Serializable {


     private Integer id;
     private SoftwareSystem softwareSystem;
     private String filePath;
     private String type;
     private String content;
     private Set<IrDocument> irDocuments = new HashSet<IrDocument>(0);
     private Set<ChangeSet> changeSets = new HashSet<ChangeSet>(0);

    public CodeFile() {
    }

	
    public CodeFile(SoftwareSystem softwareSystem, String filePath, String type) {
        this.softwareSystem = softwareSystem;
        this.filePath = filePath;
        this.type = type;
    }
    public CodeFile(SoftwareSystem softwareSystem, String filePath, String type, String content, Set<IrDocument> irDocuments, Set<ChangeSet> changeSets) {
       this.softwareSystem = softwareSystem;
       this.filePath = filePath;
       this.type = type;
       this.content = content;
       this.irDocuments = irDocuments;
       this.changeSets = changeSets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="system_id", nullable=false)
    public SoftwareSystem getSoftwareSystem() {
        return this.softwareSystem;
    }
    
    public void setSoftwareSystem(SoftwareSystem softwareSystem) {
        this.softwareSystem = softwareSystem;
    }

    
    @Column(name="file_path", nullable=false, length=800)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    
    @Column(name="type", nullable=false, length=200)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="content")
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="codeFile")
    public Set<IrDocument> getIrDocuments() {
        return this.irDocuments;
    }
    
    public void setIrDocuments(Set<IrDocument> irDocuments) {
        this.irDocuments = irDocuments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="codeFile")
    public Set<ChangeSet> getChangeSets() {
        return this.changeSets;
    }
    
    public void setChangeSets(Set<ChangeSet> changeSets) {
        this.changeSets = changeSets;
    }




}


