package seers.irda.entity;
// Generated Nov 19, 2015 11:09:07 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IrDocument generated by hbm2java
 */
@Entity
@Table(name="ir_document"
    ,catalog="ir_issues"
    , uniqueConstraints = @UniqueConstraint(columnNames={"name", "revision_id"}) 
)
public class IrDocument  implements java.io.Serializable {


     private Integer id;
     private CodeFile codeFile;
     private Revision revision;
     private String name;
     private String txt;
     private String docType;
     private Set<IrRelevanceJudgement> irRelevanceJudgements = new HashSet<IrRelevanceJudgement>(0);

    public IrDocument() {
    }

	
    public IrDocument(CodeFile codeFile, Revision revision, String name, String txt, String docType) {
        this.codeFile = codeFile;
        this.revision = revision;
        this.name = name;
        this.txt = txt;
        this.docType = docType;
    }
    public IrDocument(CodeFile codeFile, Revision revision, String name, String txt, String docType, Set<IrRelevanceJudgement> irRelevanceJudgements) {
       this.codeFile = codeFile;
       this.revision = revision;
       this.name = name;
       this.txt = txt;
       this.docType = docType;
       this.irRelevanceJudgements = irRelevanceJudgements;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="file_id", nullable=false)
    public CodeFile getCodeFile() {
        return this.codeFile;
    }
    
    public void setCodeFile(CodeFile codeFile) {
        this.codeFile = codeFile;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="revision_id", nullable=false)
    public Revision getRevision() {
        return this.revision;
    }
    
    public void setRevision(Revision revision) {
        this.revision = revision;
    }

    
    @Column(name="name", nullable=false, length=800)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="txt", nullable=false)
    public String getTxt() {
        return this.txt;
    }
    
    public void setTxt(String txt) {
        this.txt = txt;
    }

    
    @Column(name="doc_type", nullable=false, length=200)
    public String getDocType() {
        return this.docType;
    }
    
    public void setDocType(String docType) {
        this.docType = docType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="irDocument")
    public Set<IrRelevanceJudgement> getIrRelevanceJudgements() {
        return this.irRelevanceJudgements;
    }
    
    public void setIrRelevanceJudgements(Set<IrRelevanceJudgement> irRelevanceJudgements) {
        this.irRelevanceJudgements = irRelevanceJudgements;
    }




}


