package seers.irda.entity;
// Generated Nov 19, 2015 11:09:07 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IrQuery generated by hbm2java
 */
@Entity
@Table(name="ir_query"
    ,catalog="ir_issues"
)
public class IrQuery  implements java.io.Serializable {


     private Integer id;
     private Issue issue;
     private String txt;
     private String type;
     private Set<IrRelevanceJudgement> irRelevanceJudgements = new HashSet<IrRelevanceJudgement>(0);

    public IrQuery() {
    }

	
    public IrQuery(Issue issue, String txt, String type) {
        this.issue = issue;
        this.txt = txt;
        this.type = type;
    }
    public IrQuery(Issue issue, String txt, String type, Set<IrRelevanceJudgement> irRelevanceJudgements) {
       this.issue = issue;
       this.txt = txt;
       this.type = type;
       this.irRelevanceJudgements = irRelevanceJudgements;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="issue_id", nullable=false)
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }

    
    @Column(name="txt", nullable=false)
    public String getTxt() {
        return this.txt;
    }
    
    public void setTxt(String txt) {
        this.txt = txt;
    }

    
    @Column(name="type", nullable=false, length=200)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="irQuery")
    public Set<IrRelevanceJudgement> getIrRelevanceJudgements() {
        return this.irRelevanceJudgements;
    }
    
    public void setIrRelevanceJudgements(Set<IrRelevanceJudgement> irRelevanceJudgements) {
        this.irRelevanceJudgements = irRelevanceJudgements;
    }




}


