package seers.irda.entity;
// Generated Nov 19, 2015 11:09:07 AM by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IssueRevisionId generated by hbm2java
 */
@Embeddable
public class IssueRevisionId  implements java.io.Serializable {


     private int issueId;
     private int revisionId;
     private String type;

    public IssueRevisionId() {
    }

    public IssueRevisionId(int issueId, int revisionId, String type) {
       this.issueId = issueId;
       this.revisionId = revisionId;
       this.type = type;
    }
   


    @Column(name="issue_id", nullable=false)
    public int getIssueId() {
        return this.issueId;
    }
    
    public void setIssueId(int issueId) {
        this.issueId = issueId;
    }


    @Column(name="revision_id", nullable=false)
    public int getRevisionId() {
        return this.revisionId;
    }
    
    public void setRevisionId(int revisionId) {
        this.revisionId = revisionId;
    }


    @Column(name="type", nullable=false, length=200)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IssueRevisionId) ) return false;
		 IssueRevisionId castOther = ( IssueRevisionId ) other; 
         
		 return (this.getIssueId()==castOther.getIssueId())
 && (this.getRevisionId()==castOther.getRevisionId())
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIssueId();
         result = 37 * result + this.getRevisionId();
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         return result;
   }   


}


