package seers.irda.entity;
// Generated Nov 19, 2015 11:09:07 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Issue generated by hbm2java
 */
@Entity
@Table(name="issue"
    ,catalog="ir_issues"
    , uniqueConstraints = @UniqueConstraint(columnNames={"issue_id", "system_id"}) 
)
public class Issue  implements java.io.Serializable {


     private Integer id;
     private SoftwareSystem softwareSystem;
     private String issueId;
     private String type;
     private String summary;
     private String description;
     private Date createDate;
     private String status;
     private String priority;
     private String reporter;
     private String resolution;
     private Date resolutionDate;
     private String fixversion;
     private String components;
     private String assignee;
     private Set<IssueRevision> issueRevisions = new HashSet<IssueRevision>(0);
     private Set<IrQuery> irQueries = new HashSet<IrQuery>(0);

    public Issue() {
    }

	
    public Issue(SoftwareSystem softwareSystem, String issueId, String type, String summary, Date createDate, String status, String reporter) {
        this.softwareSystem = softwareSystem;
        this.issueId = issueId;
        this.type = type;
        this.summary = summary;
        this.createDate = createDate;
        this.status = status;
        this.reporter = reporter;
    }
    public Issue(SoftwareSystem softwareSystem, String issueId, String type, String summary, String description, Date createDate, String status, String priority, String reporter, String resolution, Date resolutionDate, String fixversion, String components, String assignee, Set<IssueRevision> issueRevisions, Set<IrQuery> irQueries) {
       this.softwareSystem = softwareSystem;
       this.issueId = issueId;
       this.type = type;
       this.summary = summary;
       this.description = description;
       this.createDate = createDate;
       this.status = status;
       this.priority = priority;
       this.reporter = reporter;
       this.resolution = resolution;
       this.resolutionDate = resolutionDate;
       this.fixversion = fixversion;
       this.components = components;
       this.assignee = assignee;
       this.issueRevisions = issueRevisions;
       this.irQueries = irQueries;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="system_id", nullable=false)
    public SoftwareSystem getSoftwareSystem() {
        return this.softwareSystem;
    }
    
    public void setSoftwareSystem(SoftwareSystem softwareSystem) {
        this.softwareSystem = softwareSystem;
    }

    
    @Column(name="issue_id", nullable=false, length=200)
    public String getIssueId() {
        return this.issueId;
    }
    
    public void setIssueId(String issueId) {
        this.issueId = issueId;
    }

    
    @Column(name="type", nullable=false, length=200)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="summary", nullable=false)
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="status", nullable=false, length=200)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="priority", length=200)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    
    @Column(name="reporter", nullable=false, length=200)
    public String getReporter() {
        return this.reporter;
    }
    
    public void setReporter(String reporter) {
        this.reporter = reporter;
    }

    
    @Column(name="resolution", length=200)
    public String getResolution() {
        return this.resolution;
    }
    
    public void setResolution(String resolution) {
        this.resolution = resolution;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="resolution_date", length=19)
    public Date getResolutionDate() {
        return this.resolutionDate;
    }
    
    public void setResolutionDate(Date resolutionDate) {
        this.resolutionDate = resolutionDate;
    }

    
    @Column(name="fixversion", length=200)
    public String getFixversion() {
        return this.fixversion;
    }
    
    public void setFixversion(String fixversion) {
        this.fixversion = fixversion;
    }

    
    @Column(name="components", length=400)
    public String getComponents() {
        return this.components;
    }
    
    public void setComponents(String components) {
        this.components = components;
    }

    
    @Column(name="assignee", length=200)
    public String getAssignee() {
        return this.assignee;
    }
    
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="issue")
    public Set<IssueRevision> getIssueRevisions() {
        return this.issueRevisions;
    }
    
    public void setIssueRevisions(Set<IssueRevision> issueRevisions) {
        this.issueRevisions = issueRevisions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="issue")
    public Set<IrQuery> getIrQueries() {
        return this.irQueries;
    }
    
    public void setIrQueries(Set<IrQuery> irQueries) {
        this.irQueries = irQueries;
    }




}


