package seers.irda.entity;
// Generated Nov 19, 2015 11:09:07 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SoftwareSystem generated by hbm2java
 */
@Entity
@Table(name="software_system"
    ,catalog="ir_issues"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class SoftwareSystem  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<CodeFile> codeFiles = new HashSet<CodeFile>(0);
     private Set<Revision> revisions = new HashSet<Revision>(0);
     private Set<Issue> issues = new HashSet<Issue>(0);

    public SoftwareSystem() {
    }

	
    public SoftwareSystem(String name) {
        this.name = name;
    }
    public SoftwareSystem(String name, Set<CodeFile> codeFiles, Set<Revision> revisions, Set<Issue> issues) {
       this.name = name;
       this.codeFiles = codeFiles;
       this.revisions = revisions;
       this.issues = issues;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="softwareSystem")
    public Set<CodeFile> getCodeFiles() {
        return this.codeFiles;
    }
    
    public void setCodeFiles(Set<CodeFile> codeFiles) {
        this.codeFiles = codeFiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="softwareSystem")
    public Set<Revision> getRevisions() {
        return this.revisions;
    }
    
    public void setRevisions(Set<Revision> revisions) {
        this.revisions = revisions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="softwareSystem")
    public Set<Issue> getIssues() {
        return this.issues;
    }
    
    public void setIssues(Set<Issue> issues) {
        this.issues = issues;
    }




}


