package seers.irda.entity;
// Generated Dec 9, 2015 11:27:45 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VChangeSetId generated by hbm2java
 */
@Embeddable
public class VChangeSetId  implements java.io.Serializable {


     private int revisionId;
     private String commitId;
     private String revisionMsg;
     private String revisionAuthor;
     private Date revisionDate;
     private int fileId;
     private String filePath;
     private String fileType;
     private String fileContent;
     private String changeType;
     private int systemId;

    public VChangeSetId() {
    }

	
    public VChangeSetId(int revisionId, String commitId, String revisionMsg, String revisionAuthor, Date revisionDate, int fileId, String filePath, String fileType, String changeType, int systemId) {
        this.revisionId = revisionId;
        this.commitId = commitId;
        this.revisionMsg = revisionMsg;
        this.revisionAuthor = revisionAuthor;
        this.revisionDate = revisionDate;
        this.fileId = fileId;
        this.filePath = filePath;
        this.fileType = fileType;
        this.changeType = changeType;
        this.systemId = systemId;
    }
    public VChangeSetId(int revisionId, String commitId, String revisionMsg, String revisionAuthor, Date revisionDate, int fileId, String filePath, String fileType, String fileContent, String changeType, int systemId) {
       this.revisionId = revisionId;
       this.commitId = commitId;
       this.revisionMsg = revisionMsg;
       this.revisionAuthor = revisionAuthor;
       this.revisionDate = revisionDate;
       this.fileId = fileId;
       this.filePath = filePath;
       this.fileType = fileType;
       this.fileContent = fileContent;
       this.changeType = changeType;
       this.systemId = systemId;
    }
   


    @Column(name="revision_id", nullable=false)
    public int getRevisionId() {
        return this.revisionId;
    }
    
    public void setRevisionId(int revisionId) {
        this.revisionId = revisionId;
    }


    @Column(name="commit_id", nullable=false, length=200)
    public String getCommitId() {
        return this.commitId;
    }
    
    public void setCommitId(String commitId) {
        this.commitId = commitId;
    }


    @Column(name="revision_msg", nullable=false)
    public String getRevisionMsg() {
        return this.revisionMsg;
    }
    
    public void setRevisionMsg(String revisionMsg) {
        this.revisionMsg = revisionMsg;
    }


    @Column(name="revision_author", nullable=false, length=400)
    public String getRevisionAuthor() {
        return this.revisionAuthor;
    }
    
    public void setRevisionAuthor(String revisionAuthor) {
        this.revisionAuthor = revisionAuthor;
    }


    @Column(name="revision_date", nullable=false, length=19)
    public Date getRevisionDate() {
        return this.revisionDate;
    }
    
    public void setRevisionDate(Date revisionDate) {
        this.revisionDate = revisionDate;
    }


    @Column(name="file_id", nullable=false)
    public int getFileId() {
        return this.fileId;
    }
    
    public void setFileId(int fileId) {
        this.fileId = fileId;
    }


    @Column(name="file_path", nullable=false, length=800)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }


    @Column(name="file_type", nullable=false, length=200)
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }


    @Column(name="file_content")
    public String getFileContent() {
        return this.fileContent;
    }
    
    public void setFileContent(String fileContent) {
        this.fileContent = fileContent;
    }


    @Column(name="change_type", nullable=false, length=200)
    public String getChangeType() {
        return this.changeType;
    }
    
    public void setChangeType(String changeType) {
        this.changeType = changeType;
    }


    @Column(name="system_id", nullable=false)
    public int getSystemId() {
        return this.systemId;
    }
    
    public void setSystemId(int systemId) {
        this.systemId = systemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VChangeSetId) ) return false;
		 VChangeSetId castOther = ( VChangeSetId ) other; 
         
		 return (this.getRevisionId()==castOther.getRevisionId())
 && ( (this.getCommitId()==castOther.getCommitId()) || ( this.getCommitId()!=null && castOther.getCommitId()!=null && this.getCommitId().equals(castOther.getCommitId()) ) )
 && ( (this.getRevisionMsg()==castOther.getRevisionMsg()) || ( this.getRevisionMsg()!=null && castOther.getRevisionMsg()!=null && this.getRevisionMsg().equals(castOther.getRevisionMsg()) ) )
 && ( (this.getRevisionAuthor()==castOther.getRevisionAuthor()) || ( this.getRevisionAuthor()!=null && castOther.getRevisionAuthor()!=null && this.getRevisionAuthor().equals(castOther.getRevisionAuthor()) ) )
 && ( (this.getRevisionDate()==castOther.getRevisionDate()) || ( this.getRevisionDate()!=null && castOther.getRevisionDate()!=null && this.getRevisionDate().equals(castOther.getRevisionDate()) ) )
 && (this.getFileId()==castOther.getFileId())
 && ( (this.getFilePath()==castOther.getFilePath()) || ( this.getFilePath()!=null && castOther.getFilePath()!=null && this.getFilePath().equals(castOther.getFilePath()) ) )
 && ( (this.getFileType()==castOther.getFileType()) || ( this.getFileType()!=null && castOther.getFileType()!=null && this.getFileType().equals(castOther.getFileType()) ) )
 && ( (this.getFileContent()==castOther.getFileContent()) || ( this.getFileContent()!=null && castOther.getFileContent()!=null && this.getFileContent().equals(castOther.getFileContent()) ) )
 && ( (this.getChangeType()==castOther.getChangeType()) || ( this.getChangeType()!=null && castOther.getChangeType()!=null && this.getChangeType().equals(castOther.getChangeType()) ) )
 && (this.getSystemId()==castOther.getSystemId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRevisionId();
         result = 37 * result + ( getCommitId() == null ? 0 : this.getCommitId().hashCode() );
         result = 37 * result + ( getRevisionMsg() == null ? 0 : this.getRevisionMsg().hashCode() );
         result = 37 * result + ( getRevisionAuthor() == null ? 0 : this.getRevisionAuthor().hashCode() );
         result = 37 * result + ( getRevisionDate() == null ? 0 : this.getRevisionDate().hashCode() );
         result = 37 * result + this.getFileId();
         result = 37 * result + ( getFilePath() == null ? 0 : this.getFilePath().hashCode() );
         result = 37 * result + ( getFileType() == null ? 0 : this.getFileType().hashCode() );
         result = 37 * result + ( getFileContent() == null ? 0 : this.getFileContent().hashCode() );
         result = 37 * result + ( getChangeType() == null ? 0 : this.getChangeType().hashCode() );
         result = 37 * result + this.getSystemId();
         return result;
   }   


}


