package seers.irda.entity;
// Generated Dec 9, 2015 11:27:45 AM by Hibernate Tools 4.3.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VChangeSet generated by hbm2java
 */
@Entity
@Table(name="v_change_set"
    ,catalog="ir_issues"
)
public class VChangeSet  implements java.io.Serializable {


     private VChangeSetId id;

    public VChangeSet() {
    }

    public VChangeSet(VChangeSetId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="revisionId", column=@Column(name="revision_id", nullable=false) ), 
        @AttributeOverride(name="commitId", column=@Column(name="commit_id", nullable=false, length=200) ), 
        @AttributeOverride(name="revisionMsg", column=@Column(name="revision_msg", nullable=false) ), 
        @AttributeOverride(name="revisionAuthor", column=@Column(name="revision_author", nullable=false, length=400) ), 
        @AttributeOverride(name="revisionDate", column=@Column(name="revision_date", nullable=false, length=19) ), 
        @AttributeOverride(name="fileId", column=@Column(name="file_id", nullable=false) ), 
        @AttributeOverride(name="filePath", column=@Column(name="file_path", nullable=false, length=800) ), 
        @AttributeOverride(name="fileType", column=@Column(name="file_type", nullable=false, length=200) ), 
        @AttributeOverride(name="fileContent", column=@Column(name="file_content") ), 
        @AttributeOverride(name="changeType", column=@Column(name="change_type", nullable=false, length=200) ), 
        @AttributeOverride(name="systemId", column=@Column(name="system_id", nullable=false) ) } )
    public VChangeSetId getId() {
        return this.id;
    }
    
    public void setId(VChangeSetId id) {
        this.id = id;
    }




}


