package seers.irda.entity;
// Generated Dec 9, 2015 11:27:45 AM by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VIrQueryId generated by hbm2java
 */
@Embeddable
public class VIrQueryId  implements java.io.Serializable {


     private int queryId;
     private String queryTxt;
     private String queryType;
     private int issueId;
     private int systemId;

    public VIrQueryId() {
    }

    public VIrQueryId(int queryId, String queryTxt, String queryType, int issueId, int systemId) {
       this.queryId = queryId;
       this.queryTxt = queryTxt;
       this.queryType = queryType;
       this.issueId = issueId;
       this.systemId = systemId;
    }
   


    @Column(name="query_id", nullable=false)
    public int getQueryId() {
        return this.queryId;
    }
    
    public void setQueryId(int queryId) {
        this.queryId = queryId;
    }


    @Column(name="query_txt", nullable=false)
    public String getQueryTxt() {
        return this.queryTxt;
    }
    
    public void setQueryTxt(String queryTxt) {
        this.queryTxt = queryTxt;
    }


    @Column(name="query_type", nullable=false, length=200)
    public String getQueryType() {
        return this.queryType;
    }
    
    public void setQueryType(String queryType) {
        this.queryType = queryType;
    }


    @Column(name="issue_id", nullable=false)
    public int getIssueId() {
        return this.issueId;
    }
    
    public void setIssueId(int issueId) {
        this.issueId = issueId;
    }


    @Column(name="system_id", nullable=false)
    public int getSystemId() {
        return this.systemId;
    }
    
    public void setSystemId(int systemId) {
        this.systemId = systemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VIrQueryId) ) return false;
		 VIrQueryId castOther = ( VIrQueryId ) other; 
         
		 return (this.getQueryId()==castOther.getQueryId())
 && ( (this.getQueryTxt()==castOther.getQueryTxt()) || ( this.getQueryTxt()!=null && castOther.getQueryTxt()!=null && this.getQueryTxt().equals(castOther.getQueryTxt()) ) )
 && ( (this.getQueryType()==castOther.getQueryType()) || ( this.getQueryType()!=null && castOther.getQueryType()!=null && this.getQueryType().equals(castOther.getQueryType()) ) )
 && (this.getIssueId()==castOther.getIssueId())
 && (this.getSystemId()==castOther.getSystemId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getQueryId();
         result = 37 * result + ( getQueryTxt() == null ? 0 : this.getQueryTxt().hashCode() );
         result = 37 * result + ( getQueryType() == null ? 0 : this.getQueryType().hashCode() );
         result = 37 * result + this.getIssueId();
         result = 37 * result + this.getSystemId();
         return result;
   }   


}


