package seers.irda.entity;
// Generated Dec 9, 2015 11:27:45 AM by Hibernate Tools 4.3.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VIrQuery generated by hbm2java
 */
@Entity
@Table(name="v_ir_query"
    ,catalog="ir_issues"
)
public class VIrQuery  implements java.io.Serializable {


     private VIrQueryId id;

    public VIrQuery() {
    }

    public VIrQuery(VIrQueryId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="queryId", column=@Column(name="query_id", nullable=false) ), 
        @AttributeOverride(name="queryTxt", column=@Column(name="query_txt", nullable=false) ), 
        @AttributeOverride(name="queryType", column=@Column(name="query_type", nullable=false, length=200) ), 
        @AttributeOverride(name="issueId", column=@Column(name="issue_id", nullable=false) ), 
        @AttributeOverride(name="systemId", column=@Column(name="system_id", nullable=false) ) } )
    public VIrQueryId getId() {
        return this.id;
    }
    
    public void setId(VIrQueryId id) {
        this.id = id;
    }




}


