package seers.irda.entity;
// Generated Dec 9, 2015 11:27:45 AM by Hibernate Tools 4.3.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VIrRelevanceJudgement generated by hbm2java
 */
@Entity
@Table(name="v_ir_relevance_judgement"
    ,catalog="ir_issues"
)
public class VIrRelevanceJudgement  implements java.io.Serializable {


     private VIrRelevanceJudgementId id;

    public VIrRelevanceJudgement() {
    }

    public VIrRelevanceJudgement(VIrRelevanceJudgementId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="queryId", column=@Column(name="query_id", nullable=false) ), 
        @AttributeOverride(name="queryTxt", column=@Column(name="query_txt", nullable=false) ), 
        @AttributeOverride(name="queryType", column=@Column(name="query_type", nullable=false, length=200) ), 
        @AttributeOverride(name="issueId", column=@Column(name="issue_id", nullable=false) ), 
        @AttributeOverride(name="docId", column=@Column(name="doc_id", nullable=false) ), 
        @AttributeOverride(name="docName", column=@Column(name="doc_name", nullable=false, length=800) ), 
        @AttributeOverride(name="docTxt", column=@Column(name="doc_txt", nullable=false) ), 
        @AttributeOverride(name="docType", column=@Column(name="doc_type", nullable=false, length=200) ), 
        @AttributeOverride(name="fileId", column=@Column(name="file_id", nullable=false) ), 
        @AttributeOverride(name="revisionId", column=@Column(name="revision_id", nullable=false) ) } )
    public VIrRelevanceJudgementId getId() {
        return this.id;
    }
    
    public void setId(VIrRelevanceJudgementId id) {
        this.id = id;
    }




}


